version: "3.9"

services:
  myapp:
    image: bitnami/codeigniter
    ports: 
      - "8081:8000"
    volumes: 
      - ".:/app"
    depends_on:
      - mariadb
  mariadb:
    image: bitnami/mariadb
    ports:
      - "1235:3306"
    environment:
      #- ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=example
    volumes:
      - mariadb-data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always

volumes:
  mariadb-data: